on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: npm install && npm run build
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: uzTJ7Utj8qUdlF2US6sh8PFOB5krXv6RTew2tCP4
          accountId: 7e97f7aa2efdef8a1685a92f15feecc5
          projectName: todotest
          directory: dist
